### ISSUE TITLE
Problem with Setting up bot

### ISSUE THREAD

**Issue by nco795** [busheezy/server-redirect-node-steam-bot#3]
npm ERR! server-redirect-node-steam-bot@1.1.5 start: `node app.js`
npm ERR! Exit status 127
npm ERR!
npm ERR! Failed at the server-redirect-node-steam-bot@1.1.5 start script.
npm ERR! This is most likely a problem with the server-redirect-node-steam-bot package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls server-redirect-node-steam-bot
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/steambot/server-redirect-node-steam-bot
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/steambot/server-redirect-node-steam-bot/npm-debug.log
npm ERR! not ok code 0

**Comment by nco795** [comment]
Its working now with node 4.2.1

**Comment by busheezy** [comment]
Closing. Let me know if you still have issues.
